### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by dev-ns8** [chermehdi/eunomia#4]
Was browsing this repo and had a quick question about your encoder. 

I don't use bitshifts much, but have noticed their used in many DB / KVs.

I was wondering if you could explain this bit of code and why you're shifting the values bits consecutively by multiples of 8? 

(from encoding.go)

`func WriteLong(file io.WriterAt, offset int64, value int64) (int64, error) {

	buffer[0] = byte(value >> 56)
	buffer[1] = byte(value >> 48)
	buffer[2] = byte(value >> 40)
	buffer[3] = byte(value >> 32)
	buffer[4] = byte(value >> 24)
	buffer[5] = byte(value >> 16)
	buffer[6] = byte(value >> 8)
	buffer[7] = byte(value)
	written, err := file.WriteAt(buffer[0:8], offset)`

**Comment by chermehdi** [comment]
To write a an unsigned integer with 64 bit width into a byte stream, you will need to write it into 8 bytes where each byte will hold 8 bits. In the code above, if you shift the value by 56 you are left with highest 8 bits and a bunch of leading zeros which when cast to a byte a trimmed, so you can extract the highest 8 bits, the second highest 8 bits can be extracted by doing the same but this time getting the hightest 16 bits (by shifting right by 48) and casting the higher bits (the 0 paddings and high 8 bits).

I hope this helps.
